### ISSUE TITLE
Support json.RawMessage

### ISSUE THREAD

**Issue by sschepens** [json-iterator/go#63]
There doesn't seem to be supprot for `json.RawMessage`, using it raises all sorts of undefined behaviors.

**Comment by taowen** [comment]
https://github.com/json-iterator/go/blob/master/jsoniter_raw_message_test.go

It seems like working fine. Can you give me a bad case?

**Comment by sschepens** [comment]
First,
Unmarshaling into a type with `*json.RawMessage` crashes the program, such as `map[string]*json.RawMessage`.

This code triggers the issue:
```go
import "github.com/json-iterator/go"                                                                                                                                                
import "encoding/json"                                                                                                                                                              
import "fmt"                                                                                                                                                                        
                                                                                                                                                                                    
type RawMap map[string]*json.RawMessage                                                                                                                                             
type Inner struct {                                                                                                                                                                 
        Key string `json:"key"`                                                                                                                                                     
}                                                                                                                                                                                   
                                                                                                                                                                                    
func main() {                                                                                                                                                                       
        b := []byte("{\"test\":[{\"key\":\"value\"}]}")                                                                                                                             
        var rawMap RawMap                                                                                                                                                           
        jsoniter.Unmarshal(b, &rawMap)                                                                                                                                              
        fmt.Printf("Test: %s\n", *rawMap["test"])                                                                                                                                   
        var inner []Inner                                                                                                                                                           
        jsoniter.Unmarshal(*rawMap["test"], &inner)                                                                                                                                 
        fmt.Printf("Inner: %+v\n", inner)                                                                                                                                           
}    
```
Crashes with:
```
unexpected fault address 0xc4205974af
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc4205974af pc=0x491494]
```

The other thing that seems to not be working compatibly with stdlib json is unmarshaling a composed struct:
```go
import "github.com/json-iterator/go"                                                                                                                                                
import "encoding/json"                                                                                                                                                              
import "fmt"                                                                                                                                                                        
                                                                                                                                                                                    
type Inner struct {                                                                                                                                                                 
        Key string `json:"key"`                                                                                                                                                     
}                                                                                                                                                                                   
                                                                                                                                                                                    
type Outer struct {                                                                                                                                                                 
        Inner                                                                                                                                                                       
}                                                                                                                                                                                   
                                                                                                                                                                                    
func main() {                                                                                                                                                                       
        var outer Outer                                                                                                                                                             
        j := []byte("{\"key\":\"value\"}")                                                                                                                                          
        jsoniter.Unmarshal(j, &outer)                                                                                                                                               
        fmt.Printf("jsoniter: %+v\n", outer)                                                                                                                                        
        json.Unmarshal(j, &outer)                                                                                                                                                   
        fmt.Printf("json: %+v\n", outer)                                                                                                                                            
}
```
This prints:
```
jsoniter: {Inner:{Key:}}
json: {Inner:{Key:value}}
```

With stdlib json inner struct gets populated, while with jsoniter it doesn't, I'm assuming jsoniter is expecting nested fields.

**Comment by sschepens** [comment]
Also,
It would be great if `jsoniter` could expose a type `jsoniter.RawMessage` for compatibility with json stdlib so that one could replace `import "encoding/json"` with `import json"github.com/json-iterator/go"`

**Comment by taowen** [comment]
should be all fixed now

**Comment by sschepens** [comment]
Seems ok, but I'm having a crash when serializing a type which implements `Marshaler` and contains a a string aliased type.
This code reproduces the error:
```go
package main                                                                                                                                                                        
                                                                                                                                                                                    
import "github.com/json-iterator/go"                                                                                                                                                
import "encoding/json"                                                                                                                                                              
import "fmt"                                                                                                                                                                        
                                                                                                                                                                                    
type String string                                                                                                                                                                  
                                                                                                                                                                                    
const (                                                                                                                                                                             
        S String = "string"                                                                                                                                                         
)                                                                                                                                                                                   
                                                                                                                                                                                    
type Struct struct {                                                                                                                                                                
        String String                                                                                                                                                               
}                                                                                                                                                                                   
                                                                                                                                                                                    
func (s Struct) MarshalJSON() ([]byte, error) {                                                                                                                                     
        var b []byte                                                                                                                                                                
        b = append(b, '"')                                                                                                                                                          
        b = append(b, s.String...)                                                                                                                                                  
        b = append(b, '"')                                                                                                                                                          
        return b, nil                                                                                                                                                               
}                                                                                                                                                                                   
                                                                                                                                                                                    
func main() {                                                                                                                                                                       
        fixed := Struct{S}                                                                                                                                                          
        b, err := json.Marshal(fixed)                                                                                                                                               
        if err != nil {                                                                                                                                                             
                panic(err)                                                                                                                                                          
        }                                                                                                                                                                           
        fmt.Printf("json: %s\n", b)                                                                                                                                                 
        b, err = jsoniter.Marshal(fixed)                                                                                                                                            
        if err != nil {                                                                                                                                                             
                panic(err)                                                                                                                                                          
        }                                                                                                                                                                           
        fmt.Printf("jsoniter: %s\n", b)                                                                                                                                             
}
```

Panics with:
```
panic: runtime error: growslice: cap out of range
```

But only when serializing with `jsoniter`, stdlib json works just fine

**Comment by taowen** [comment]
should be fixed now

**Comment by sschepens** [comment]
@taowen nested struct marshaling is still wrong:
```go
package main

import "fmt"
import "encoding/json"
import "github.com/json-iterator/go"

type Base struct {
	Type string `json:"type"`
}

type Struct struct {
	Field string `json:"field"`
	FieldType string `json:"field_type"`
	Base
}

func main() {
	s := Struct{Field: "field", FieldType: "field_type", Base: Base{"type"}}
	b, err := json.Marshal(s)
	if err != nil {
		panic(err)
	}
	fmt.Printf("json: %s\n",b)
	b, err = jsoniter.Marshal(s)
	if err != nil {
		panic(err)
	}
	fmt.Printf("jsoniter: %s\n",b)
}
```

This code prints the following:
```
json: {"field":"field","field_type":"field_type","type":"type"}
jsoniter: {"type":"field","field":"field","field_type":"field_type"}
```

First of all, stdlib json follows the struct order and serializes nested fields last, because it is last in the struct. Second, jsoniter is somehow assigning the value of field  `Type` to the value of field `Field`.

**Comment by taowen** [comment]
should be fixed now. I made wrong assumption.
